version: 0.2   

phases:
  install:
    runtime-versions:
      python: 3.8 #it will install python 3.8 on the server
  pre_build:
    commands:
      -echo We ARE ENTERING THE PREBUILD PHASE...
      -echo checking the python version installed
      -python --version
  build:
    commands:
      -echo **** Build on `date` ***** 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
   files:
     - '**/*' # zip back everythin up 
     